// Mocks generated by Mockito 5.4.4 from annotations
// in auth_clean_arch/test/features/registration/presentation/verify_email_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:auth_clean_arch/core/errors/failures.dart' as _i8;
import 'package:auth_clean_arch/core/services/email_service.dart' as _i3;
import 'package:auth_clean_arch/core/usecases/usecase.dart' as _i9;
import 'package:auth_clean_arch/core/utils/validators/email_validator.dart'
    as _i10;
import 'package:auth_clean_arch/features/registration/domain/entities/user.dart'
    as _i5;
import 'package:auth_clean_arch/features/registration/domain/repositories/user_repository.dart'
    as _i2;
import 'package:auth_clean_arch/features/registration/domain/use_cases/verify_email_use_case.dart'
    as _i6;
import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerificationEmailService_1 extends _i1.SmartFake
    implements _i3.VerificationEmailService {
  _FakeVerificationEmailService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_3 extends _i1.SmartFake implements _i5.User {
  _FakeUser_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VerifyEmailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyEmailUseCase extends _i1.Mock
    implements _i6.VerifyEmailUseCase {
  MockVerifyEmailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set verificationCode(String? _verificationCode) => super.noSuchMethod(
        Invocation.setter(
          #verificationCode,
          _verificationCode,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set sentTime(DateTime? _sentTime) => super.noSuchMethod(
        Invocation.setter(
          #sentTime,
          _sentTime,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.UserRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.UserRepository);

  @override
  set repository(_i2.UserRepository? _repository) => super.noSuchMethod(
        Invocation.setter(
          #repository,
          _repository,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.VerificationEmailService get verificationEmailService =>
      (super.noSuchMethod(
        Invocation.getter(#verificationEmailService),
        returnValue: _FakeVerificationEmailService_1(
          this,
          Invocation.getter(#verificationEmailService),
        ),
      ) as _i3.VerificationEmailService);

  @override
  set verificationEmailService(
          _i3.VerificationEmailService? _verificationEmailService) =>
      super.noSuchMethod(
        Invocation.setter(
          #verificationEmailService,
          _verificationEmailService,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set emailToVerify(String? _emailToVerify) => super.noSuchMethod(
        Invocation.setter(
          #emailToVerify,
          _emailToVerify,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i4.Either<_i8.Failure, String>> call(_i9.EmailParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i7.Future<_i4.Either<_i8.Failure, String>>.value(
            _FakeEither_2<_i8.Failure, String>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<_i4.Either<_i8.Failure, String>>);

  @override
  _i7.Future<_i4.Either<_i8.Failure, String>> sendEmail(
          _i9.EmailParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmail,
          [params],
        ),
        returnValue: _i7.Future<_i4.Either<_i8.Failure, String>>.value(
            _FakeEither_2<_i8.Failure, String>(
          this,
          Invocation.method(
            #sendEmail,
            [params],
          ),
        )),
      ) as _i7.Future<_i4.Either<_i8.Failure, String>>);

  @override
  bool verifyInputCode(String? inputCode) => (super.noSuchMethod(
        Invocation.method(
          #verifyInputCode,
          [inputCode],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<_i4.Either<_i8.Failure, _i5.User>> verifyEmail(
          String? inputCode) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [inputCode],
        ),
        returnValue: _i7.Future<_i4.Either<_i8.Failure, _i5.User>>.value(
            _FakeEither_2<_i8.Failure, _i5.User>(
          this,
          Invocation.method(
            #verifyEmail,
            [inputCode],
          ),
        )),
      ) as _i7.Future<_i4.Either<_i8.Failure, _i5.User>>);

  @override
  _i5.User updateVerifiedEmailField(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateVerifiedEmailField,
          [user],
        ),
        returnValue: _FakeUser_3(
          this,
          Invocation.method(
            #updateVerifiedEmailField,
            [user],
          ),
        ),
      ) as _i5.User);
}

/// A class which mocks [EmailValidator].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailValidator extends _i1.Mock implements _i10.EmailValidator {
  MockEmailValidator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Either<_i8.Failure, String> validate(String? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #validate,
          [value],
        ),
        returnValue: _FakeEither_2<_i8.Failure, String>(
          this,
          Invocation.method(
            #validate,
            [value],
          ),
        ),
      ) as _i4.Either<_i8.Failure, String>);
}
