// Mocks generated by Mockito 5.4.4 from annotations
// in auth_clean_arch/test/features/registration/data/repositories/user_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:auth_clean_arch/features/registration/data/datasources/local_db_datasource.dart'
    as _i5;
import 'package:auth_clean_arch/features/registration/data/datasources/local_shared_pref_datasource.dart'
    as _i3;
import 'package:auth_clean_arch/features/registration/data/models/user_create_model.dart'
    as _i6;
import 'package:auth_clean_arch/features/registration/data/models/user_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocalSharedPrefDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalSharedPrefDatasource extends _i1.Mock
    implements _i3.LocalSharedPrefDatasource {
  MockLocalSharedPrefDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> cache(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cache,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: 0,
      ) as int);
}

/// A class which mocks [UserModelLocalDbDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserModelLocalDbDatasource extends _i1.Mock
    implements _i5.UserModelLocalDbDatasource {
  MockUserModelLocalDbDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> createUser(_i6.UserCreateModel? user) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [user],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.UserModel> getUserById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [id],
        ),
        returnValue: _i4.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #getUserById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<_i2.UserModel> getUserByEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserByEmail,
          [email],
        ),
        returnValue: _i4.Future<_i2.UserModel>.value(_FakeUserModel_0(
          this,
          Invocation.method(
            #getUserByEmail,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<bool> setEmailVerification(
    int? id,
    bool? verified,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setEmailVerification,
          [
            id,
            verified,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateLastLogin(
    int? id,
    DateTime? dateTime,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastLogin,
          [
            id,
            dateTime,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> changePassword(
    int? id,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [
            id,
            password,
          ],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateUser(_i2.UserModel? userModel) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [userModel],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteUser(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
