// Mocks generated by Mockito 5.4.4 from annotations
// in auth_clean_arch/test/features/registration/domain/usecases/login_usecase/login_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:auth_clean_arch/core/utils/encryption.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PasswordHashingUtil].
///
/// See the documentation for Mockito's code generation for more information.
class MockPasswordHashingUtil extends _i1.Mock
    implements _i2.PasswordHashingUtil {
  MockPasswordHashingUtil() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String hash(String? password) => (super.noSuchMethod(
        Invocation.method(
          #hash,
          [password],
        ),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.method(
            #hash,
            [password],
          ),
        ),
      ) as String);

  @override
  bool verifyPassword(
    String? inputPassword,
    String? hashedPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPassword,
          [
            inputPassword,
            hashedPassword,
          ],
        ),
        returnValue: false,
      ) as bool);
}
